[SERVICE]
    Flush        1
    Log_Level    info
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_Port    2020
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name         forward
    Listen       0.0.0.0
    Port         24224

[FILTER]
    Name         parser
    Match        *
    Key_Name     log
    Parser       json
    Reserve_Data On

[FILTER]
    Name         record_modifier
    Match        *
    Record       service.name fluent-bit-example
    Record       deployment.environment dev
    Record       k8s.cluster.name local-test

[OUTPUT]
    Name                 opentelemetry
    Match                *
    Host                 otel-collector
    Port                 4318
    Logs_uri             /v1/logs
    Tls                  Off
    Log_Response_Payload True

[OUTPUT]
    Name                 stdout
    Match                *
    Format               json_lines
