receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"

processors:
  memory_limiter:
    check_interval: 5s
    limit_percentage: 85
    spike_limit_percentage: 15
  resource:
    attributes:
      - key: service.name
        value: "fluent-bit-example"
        action: upsert
      - key: deployment.environment
        value: "dev"
        action: upsert
      - key: k8s.cluster.name
        value: "local-test"
        action: upsert
  batch:
    timeout: 5s
    send_batch_size: 100000

exporters:
  otlphttp:
    endpoint: "https://${env:LAST9_HOST}"
    headers:
      Authorization: "Basic ${env:LAST9_AUTH}"
  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlphttp, debug]
