-- Create user last9
CREATE USER last9 IDENTIFIED BY last9;

-- Grant privileges to last9
GRANT CREATE SESSION TO last9;
GRANT CONNECT, SELECT_CATALOG_ROLE TO last9;
GRANT SELECT ON V_$SESSION TO last9;
GRANT SELECT ON V_$SYSSTAT TO last9;
GRANT SELECT ON V_$SYSTEM_EVENT TO last9;
GRANT SELECT ON V_$PROCESS TO last9;
GRANT SELECT ON V_$RESOURCE_LIMIT TO last9;
GRANT SELECT ON V_$SQL TO last9;
GRANT SELECT ON V_$SQLAREA TO last9;
GRANT SELECT ON V_$SQLSTATS TO last9;
GRANT SELECT ON V_$INSTANCE TO last9;
GRANT SELECT ON DBA_TABLESPACES TO last9;
GRANT SELECT ON DBA_DATA_FILES TO last9;
GRANT SELECT ON DBA_TABLESPACE_USAGE_METRICS TO last9;

-- Grant quota on USERS tablespace
ALTER USER last9 QUOTA UNLIMITED ON USERS; 