# Cloud Build configuration for Express Cloud Run service
# Usage: gcloud builds submit --config cloudbuild.yaml \
#   --substitutions=_SERVICE_NAME=my-service,_REGION=us-central1
substitutions:
  _SERVICE_NAME: cloud-run-nodejs-express
  _REGION: us-central1
  # Replace with your OTLP endpoint
  _OTLP_ENDPOINT: YOUR_OTLP_ENDPOINT

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--set-env-vars'
      - 'OTEL_SERVICE_NAME=${_SERVICE_NAME}'
      - '--set-env-vars'
      - 'OTEL_EXPORTER_OTLP_ENDPOINT=${_OTLP_ENDPOINT}'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
      - '--set-env-vars'
      - 'DEPLOYMENT_ENVIRONMENT=production'
      - '--set-env-vars'
      - 'SERVICE_VERSION=$COMMIT_SHA'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-secrets'
      - 'OTEL_EXPORTER_OTLP_HEADERS=last9-auth-header:latest'

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
