# Cloud Build configuration for Express Cloud Run service
substitutions:
  _SERVICE_NAME: express-otel-demo
  _REGION: us-central1

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--set-env-vars'
      - 'OTEL_SERVICE_NAME=${_SERVICE_NAME}'
      - '--set-env-vars'
      - 'OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp.last9.io'
      - '--set-env-vars'
      - 'DEPLOYMENT_ENVIRONMENT=production'
      - '--set-env-vars'
      - 'SERVICE_VERSION=$COMMIT_SHA'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-secrets'
      - 'OTEL_EXPORTER_OTLP_HEADERS=last9-auth-header:latest'

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
