[tox]
envlist = py{38,39}-django{32,42}, py{310,311}-django{32,42,50,51}, py{38,39,310,311}-fastapi, py{38,39,310,311}-flask
skip_missing_interpreters = true
ignore_basepython_conflict = true

[testenv]
changedir = {toxinidir}/python/django/mysite
allowlist_externals = /bin/sh
deps = Django=={env:DJANGO}
setenv =
    django32: DJANGO=3.2
    django42: DJANGO=4.2
    django50: DJANGO=5.0
    django51: DJANGO=5.1
commands_pre =
    /bin/sh -c 'pip install $(grep "^opentelemetry" {toxinidir}/python/django/mysite/requirements.txt)'
commands =
    opentelemetry-bootstrap -a install
    python manage.py check

[testenv:py{38,39,310,311}-fastapi]
changedir = {toxinidir}/python/fastapi
allowlist_externals = /bin/sh
deps = -r{toxinidir}/python/fastapi/requirements.txt
commands_pre =
    /bin/sh -c 'pip install $(grep "^opentelemetry" {toxinidir}/python/fastapi/requirements.txt)'
commands =
    opentelemetry-bootstrap -a install
    python app.py

[testenv:py{38,39,310,311}-flask]
changedir = {toxinidir}/python/flask
allowlist_externals = /bin/sh
deps = -r{toxinidir}/python/flask/requirements.txt
commands_pre =
    /bin/sh -c 'pip install $(grep "^opentelemetry" {toxinidir}/python/flask/requirements.txt || true)'
commands =
    opentelemetry-bootstrap -a install
    python app.py