[tox]
envlist = py{38,39,310,311}-django{32,42,50,51}

[testenv]
changedir = {toxinidir}/python/django/mysite
allowlist_externals = /bin/sh
deps = Django=={env:DJANGO}
setenv =
    django32: DJANGO=3.2
    django42: DJANGO=4.2
    django50: DJANGO=5.0
    django51: DJANGO=5.1
commands_pre =
    /bin/sh -c 'pip install $(grep "^opentelemetry" {toxinidir}/python/django/mysite/requirements.txt)'
commands =
    opentelemetry-bootstrap -a install
    python manage.py check
