apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: java-instrumentation
spec:
  env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://demo-collector:4318"
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "http/protobuf"
      - name: OTEL_BSP_MAX_EXPORT_BATCH_SIZE
        value: "512"
      - name: OTEL_BSP_EXPORT_TIMEOUT
        value: "2s"
      - name: OTEL_BSP_SCHEDULE_DELAY
        value: "1s"
      - name: OTEL_EXPORTER_OTLP_COMPRESSION
        value: "gzip"
      - name: OTEL_EXPORTER_OTLP_TIMEOUT
        value: "10s"
      - name: OTEL_METRICS_EXPORTER
        value: "none"
      - name: OTEL_LOGS_EXPORTER
        value: "none"
  exporter:
    endpoint: http://demo-collector:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1.0"

