receivers:
  filelog:
    # File path pattern to read logs from. Update this to the destination from where you want to read logs.
    include: [/log/*.log]
    include_file_path: true
    # attributes:
      # A map of key: value pairs to add to the entry's attributes.
    # resource:
      # A map of key: value pairs to add to the entry's resource.
    retry_on_failure:
      enabled:
        true

processors:
  batch:
    timeout: 10s
    send_batch_size: 10000
    send_batch_max_size: 10000
  transform/logs:
    error_mode: ignore
    log_statements:
      - context: resource
        statements:
          - set(attributes["service.name"], "my-app") # Service name.
          - set(attributes["deployment.environment"], "staging") # Deployment Environment
  resourcedetection/system:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]
exporters:
    otlp/last9:
      endpoint: "https://otlp-aps1.last9.io:443"
      headers:
        "Authorization": "Basic bGFzdDk6bGFzdDk="
service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [batch, transform/logs, resourcedetection/system]
      exporters: [otlp/last9]

