apiVersion: v1
items:
- apiVersion: opentelemetry.io/v1beta1
  kind: OpenTelemetryCollector
  metadata:
    name: demo
  spec:
    managementState: managed
    config:
      exporters:
        debug:
          verbosity: basic
        otlp/last9:
          endpoint: https://otlp-aps1.last9.io:443
          headers:
            Authorization: Basic {{ YOUR_TOKEN }} // Replace with your token
      processors:
        batch:
          send_batch_size: 10000
          timeout: 10s
        memory_limiter:
          check_interval: 1s
          limit_percentage: 75
          spike_limit_percentage: 15
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
      service:
        pipelines:
          traces:
            exporters:
            - debug
            - otlp/last9
            processors:
            - memory_limiter
            - batch
            receivers:
            - otlp
kind: List
metadata:
  resourceVersion: ""
