# OpenTelemetry Collector DaemonSet for Log Collection
# Deploys a collector on each node to collect container logs
#
# Apply after creating the ConfigMap:
# kubectl apply -f collector-configmap.yaml
# kubectl apply -f collector-daemonset.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: last9
  labels:
    app.kubernetes.io/name: last9

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: last9
  labels:
    app.kubernetes.io/name: otel-collector

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector
  labels:
    app.kubernetes.io/name: otel-collector
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - nodes
      - nodes/stats
      - nodes/proxy
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - statefulsets
      - replicasets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector
  labels:
    app.kubernetes.io/name: otel-collector
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: last9
roleRef:
  kind: ClusterRole
  name: otel-collector
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Secret
metadata:
  name: last9-credentials
  namespace: last9
  labels:
    app.kubernetes.io/name: otel-collector
type: Opaque
stringData:
  # Replace with your Last9 credentials
  otlp-endpoint: "https://otlp.last9.io"
  auth-token: "Basic YOUR_AUTH_TOKEN_HERE"

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector
  namespace: last9
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/component: logs-collector
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otel-collector
        app.kubernetes.io/component: logs-collector
    spec:
      serviceAccountName: otel-collector
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.141.0
          args:
            - --config=/etc/otelcol/config.yaml
          ports:
            - name: otlp-grpc
              containerPort: 4317
              hostPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              hostPort: 4318
              protocol: TCP
            - name: health
              containerPort: 13133
              protocol: TCP
            - name: metrics
              containerPort: 8888
              protocol: TCP
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: LAST9_OTLP_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: last9-credentials
                  key: otlp-endpoint
            - name: LAST9_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: last9-credentials
                  key: auth-token
            - name: GOMEMLIMIT
              value: "400MiB"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /etc/otelcol
              readOnly: true
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: otel-collector-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
      # Run on all nodes including control plane
      tolerations:
        - operator: Exists

---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: last9
  labels:
    app.kubernetes.io/name: otel-collector
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
