version: '3'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:cached
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=${LAST_OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_SERVICE_NAME=my-demo-service
      - OTEL_DEPLOYMENT_ENVIRONMENT=production
      - OTEL_LOG_LEVEL=debug