# Trilogy (MySQL) for testing rails-otel-context Trilogy adapter
default: &default
  adapter: trilogy
  host: 127.0.0.1
  username: root
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_otel_dev

test:
  <<: *default
  database: rails_otel_test

production:
  <<: *default
  database: rails_otel_prod
