# Cloud Build configuration for Flask Cloud Run service
# Usage: gcloud builds submit --config cloudbuild.yaml

substitutions:
  _SERVICE_NAME: flask-otel-demo
  _REGION: us-central1

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'OTEL_SERVICE_NAME=${_SERVICE_NAME}'
      - '--set-env-vars'
      - 'OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp.last9.io'
      - '--set-env-vars'
      - 'DEPLOYMENT_ENVIRONMENT=production'
      - '--set-env-vars'
      - 'SERVICE_VERSION=$COMMIT_SHA'
      - '--set-env-vars'
      - 'CLOUD_RUN_REGION=${_REGION}'
      - '--set-secrets'
      - 'OTEL_EXPORTER_OTLP_HEADERS=last9-auth-header:latest'

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
