apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: java-instrumentation
spec:
  exporter:
    endpoint: http://otel-collector:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
    env:
      - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        value: http://otel-collector-collector:4318/v1/traces
      - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
        value: http://otel-collector-collector:4318/v1/metrics
      - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
        value: http://otel-collector-collector:4318/v1/logs
      - name: OTEL_LOGS_EXPORTER
        value: otlp
      - name: OTEL_METRICS_EXPORTER
        value: otlp
      - name: OTEL_TRACES_EXPORTER
        value: otlp
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: service.name=java-sample-app,service.version=1.0.0
      - name: OTEL_INSTRUMENTATION_SPRING_BOOT_AUTOCONFIGURE_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_COMMON_PEER_SERVICE_MAPPING
        value: ""
  resource:
    addK8sUIDAttributes: true

