# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.2'

gem 'aws-sdk-s3', '~> 1'
gem 'rexml'
gem 'opentelemetry-exporter-otlp'
gem 'opentelemetry-instrumentation-aws_lambda'
gem 'opentelemetry-instrumentation-aws_sdk'
gem 'opentelemetry-sdk'
