otel.exporter.otlp.endpoint = http://otel-collector:4317
otel.jmx.interval.milliseconds = 60000
otel.jmx.service.url = service:jmx:rmi:///jndi/rmi://cassandra:7199/jmxrmi
otel.jmx.target.system = cassandra
otel.metrics.exporter = otlp
