server:
  port: 8080

spring:
  application:
    name: springboot-otel-demo

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.example: INFO
    io.opentelemetry: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# OpenTelemetry configuration will be set via environment variables
# The Java agent will automatically pick up these configurations 