#!/usr/bin/env bash
#
# Regenerate the OpenTelemetry instrumentation block in a variant's requirements.txt
# by scanning installed app deps with `opentelemetry-bootstrap -a requirements`.
#
# Why: bootstrap looks at every installed package (boto3, requests, redis, ...) and
# emits matching `opentelemetry-instrumentation-*` packages — no manual auditing.
#
# Usage:
#   scripts/bootstrap-requirements.sh variants/E-pip-otel-no-layer
#
# Run locally before `chalice deploy`. Output appended to variant's requirements.txt.

set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <variant-dir>"
  echo "  e.g.: $0 variants/E-pip-otel-no-layer"
  exit 1
fi

VARIANT_DIR="$(cd "$1" && pwd)"
REQS="${VARIANT_DIR}/requirements.txt"

if [[ ! -f "${REQS}" ]]; then
  echo "FAIL: ${REQS} not found"
  exit 1
fi

# Ephemeral venv so we don't pollute the user's environment.
TMP_VENV="$(mktemp -d)/venv"
echo "Creating ephemeral venv at ${TMP_VENV}..."
python3 -m venv "${TMP_VENV}"
# shellcheck disable=SC1091
source "${TMP_VENV}/bin/activate"

echo "Installing app deps from ${REQS}..."
pip install -q --disable-pip-version-check -r "${REQS}"
echo "Installing opentelemetry-distro (provides bootstrap)..."
pip install -q --disable-pip-version-check opentelemetry-distro

OUT="$(mktemp)"
opentelemetry-bootstrap -a requirements > "${OUT}"

deactivate
rm -rf "$(dirname "${TMP_VENV}")"

echo ""
echo "Bootstrap detected the following instrumentation packages:"
echo "----"
cat "${OUT}"
echo "----"
echo ""
echo "Review the list above. Append to ${REQS}? [y/N]"
read -r answer
if [[ "${answer}" =~ ^[Yy]$ ]]; then
  {
    echo ""
    echo "# Generated by scripts/bootstrap-requirements.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    cat "${OUT}"
  } >> "${REQS}"
  echo "Appended. Review ${REQS} and de-dupe if needed before deploy."
else
  echo "Skipped. Bootstrap output left at ${OUT}"
fi
