receivers:
  nginx:
    endpoint: "http://localhost:8080/nginx_status"
    collection_interval: 10s
processors:
  batch:
    timeout: 5s
    send_batch_size: 10000
    send_batch_max_size: 10000
  resourcedetection/system:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]
  resourcedetection/ec2:
    detectors: ["ec2"]
    ec2:
      tags:
        - ^Name$
        - ^app$
  transform/hostmetrics:
    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["host.name"], resource.attributes["host.name"])
          - set(attributes["cloud.account.id"], resource.attributes["cloud.account.id"])
          - set(attributes["cloud.availability_zone"], resource.attributes["cloud.availability_zone"])
          - set(attributes["cloud.platform"], resource.attributes["cloud.platform"])
          - set(attributes["cloud.provider"], resource.attributes["cloud.provider"])
          - set(attributes["cloud.region"], resource.attributes["cloud.region"])
          - set(attributes["host.type"], resource.attributes["host.type"])
          - set(attributes["host.image.id"], resource.attributes["host.image.id"])
exporters:
  otlp/last9:
    endpoint: <last9_otlp_endpoint>
    headers:
      "Authorization": <last9_auth_header>
  debug:
    verbosity: detailed
service:
  pipelines:
    metrics:
      receivers: [nginx]
      processors: [batch, resourcedetection/system, resourcedetection/ec2, transform/hostmetrics]
      exporters: [otlp/last9, debug]
