substitutions:
  _SERVICE_NAME: cloud-run-metrics-alloy
  _REGION: us-central1
  # Replace with your Prometheus remote write URL
  _REMOTE_WRITE_URL: YOUR_REMOTE_WRITE_URL

steps:
  # Build Grafana Alloy Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.alloy'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '.'

  # Push image with commit SHA tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA']

  # Push image with latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'  # Keep warm to continuously collect metrics
      - '--max-instances'
      - '1'  # Only need one instance
      - '--timeout'
      - '600'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID'
      - '--set-env-vars'
      - 'REMOTE_WRITE_URL=${_REMOTE_WRITE_URL}'
      - '--set-secrets'
      - 'LAST9_USERNAME=last9-username:latest'
      - '--set-secrets'
      - 'LAST9_PASSWORD=last9-password:latest'
      - '--set-secrets'
      - '/secrets/gcp-creds/key.json=gcp-monitoring-credentials:latest'
      - '--set-env-vars'
      - 'GOOGLE_APPLICATION_CREDENTIALS=/secrets/gcp-creds/key.json'
      - '--service-account'
      - 'metrics-collector@$PROJECT_ID.iam.gserviceaccount.com'

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
timeout: 600s
