receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

processors:
  batch:

exporters:
  otlp:
    endpoint: "otlp.last9.io:443"
    headers:
      Authorization: "<BASIC_AUTH-HEADER>"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
