receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'mariadb'
        scrape_interval: 5s
        static_configs:
        - targets: ['localhost:9104']

exporters:
  otlp/last9:
    endpoint: "https://otlp.last9.io:443"
    headers:
      "Authorization": "Basic YOUR_AUTH_TOKEN"
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [debug, otlp/last9]
