# Datadog: PII Masking (Sensitive Data Redaction)
# Use mask_sequences to redact sensitive information before sending to Datadog
#
# This is essential for compliance (GDPR, HIPAA, PCI-DSS)

# Method 1: Pod Annotation (per-container)
---
apiVersion: v1
kind: Pod
metadata:
  name: user-service
  annotations:
    ad.datadoghq.com/app.logs: |
      [{
        "source": "nodejs",
        "service": "user-service",
        "log_processing_rules": [
          {
            "type": "mask_sequences",
            "name": "mask_ssn",
            "pattern": "\\d{3}-\\d{2}-\\d{4}",
            "replace_placeholder": "[SSN_REDACTED]"
          },
          {
            "type": "mask_sequences",
            "name": "mask_credit_card_visa",
            "pattern": "\\b4[0-9]{12}(?:[0-9]{3})?\\b",
            "replace_placeholder": "[VISA_REDACTED]"
          },
          {
            "type": "mask_sequences",
            "name": "mask_credit_card_mc",
            "pattern": "\\b5[1-5][0-9]{14}\\b",
            "replace_placeholder": "[MC_REDACTED]"
          },
          {
            "type": "mask_sequences",
            "name": "mask_credit_card_amex",
            "pattern": "\\b3[47][0-9]{13}\\b",
            "replace_placeholder": "[AMEX_REDACTED]"
          },
          {
            "type": "mask_sequences",
            "name": "mask_email",
            "pattern": "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}",
            "replace_placeholder": "[EMAIL_REDACTED]"
          },
          {
            "type": "mask_sequences",
            "name": "mask_ip_address",
            "pattern": "\\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\b",
            "replace_placeholder": "[IP_REDACTED]"
          },
          {
            "type": "mask_sequences",
            "name": "mask_phone_us",
            "pattern": "\\b\\d{3}[-.\\s]?\\d{3}[-.\\s]?\\d{4}\\b",
            "replace_placeholder": "[PHONE_REDACTED]"
          },
          {
            "type": "mask_sequences",
            "name": "mask_bearer_token",
            "pattern": "Bearer\\s+[a-zA-Z0-9._-]+",
            "replace_placeholder": "Bearer [TOKEN_REDACTED]"
          },
          {
            "type": "mask_sequences",
            "name": "mask_api_key",
            "pattern": "(api_key|apikey|api-key)[=:]\\s*[^\\s,}\"']+",
            "replace_placeholder": "$1=[REDACTED]"
          },
          {
            "type": "mask_sequences",
            "name": "mask_password",
            "pattern": "(password|passwd|pwd)[=:]\\s*[^\\s,}\"']+",
            "replace_placeholder": "$1=[REDACTED]"
          },
          {
            "type": "mask_sequences",
            "name": "mask_aws_key",
            "pattern": "AKIA[0-9A-Z]{16}",
            "replace_placeholder": "[AWS_KEY_REDACTED]"
          }
        ]
      }]
spec:
  containers:
    - name: app
      image: node:18

---
# Method 2: Global Configuration via Helm values
# datadog:
#   env:
#     - name: DD_LOGS_CONFIG_PROCESSING_RULES
#       value: >-
#         [
#           {"type":"mask_sequences","name":"mask_ssn","pattern":"\\d{3}-\\d{2}-\\d{4}","replace_placeholder":"[SSN]"},
#           {"type":"mask_sequences","name":"mask_email","pattern":"[\\w.+-]+@[\\w.-]+\\.[a-zA-Z]{2,}","replace_placeholder":"[EMAIL]"},
#           {"type":"mask_sequences","name":"mask_ip","pattern":"\\b(?:(?:25[0-5]|2[0-4]\\d|[01]?\\d\\d?)\\.){3}(?:25[0-5]|2[0-4]\\d|[01]?\\d\\d?)\\b","replace_placeholder":"[IP]"}
#         ]
