source "https://rubygems.org"

ruby "3.3.3"

gem "rails", "~> 7.1.3"
gem "puma", ">= 5.0"

# Stripe SDK
gem "stripe", "~> 13.0"

# CORS — allows the React frontend to call this API
gem "rack-cors"

# OpenTelemetry — traces
gem "opentelemetry-sdk"
gem "opentelemetry-exporter-otlp"
gem "opentelemetry-instrumentation-all"

# OpenTelemetry — logs
gem "opentelemetry-logs-sdk"
gem "opentelemetry-exporter-otlp-logs"

# Environment variables
gem "dotenv-rails", groups: [:development, :test]

gem "tzinfo-data", platforms: %i[mswin mswin64 mingw x64_mingw jruby]
gem "bootsnap", require: false
