receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: postgres-exporter
          scrape_interval: 60s
          static_configs:
            - targets: ["postgres-exporter:9187"]

processors:
  batch:
    timeout: 10s
    send_batch_size: 10000
  resourcedetection:
    detectors: [env, system, docker, ec2, azure, gcp]
    timeout: 2s
  resource:
    attributes:
      - key: db_name
        value: postgres-db
        action: upsert
      - key: deployment.environment
        value: dev
        action: upsert

exporters:
  otlp/last9:
    endpoint: "<LAST9_OTLP_ENDPOINT>"  # Replace with actual Last9 endpoint if different
    headers:
      "Authorization": "Basic <LAST9_OTLP_AUTH_HEADER>"
  
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [resourcedetection, resource, batch]
      exporters: [otlp/last9]

  telemetry:
    logs:
      level: info
