receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'yace'
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:5000']

processors:
  batch:
    timeout: 5s
    send_batch_size: 5000
    send_batch_max_size: 5000

exporters:
  otlp/last9:
    endpoint: <last9_otlp_endpoint>
    headers:
      "Authorization": <last9_auth_header>
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [otlp/last9]