receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'yace'
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:5000']

processors:
  filter:
    metrics:
      include:
        match_type: regexp
        metric_names:
          - ".*"  # Include all metrics

  attributes:
    actions:
      - key: scraper
        value: "yace"
        action: insert

exporters:
  otlp/last9:
    endpoint: <last9_otlp_endpoint>
    headers:
      "Authorization": <last9_auth_header>
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [filter, attributes]
      exporters: [debug, otlp/last9]