apiVersion: v1alpha1
discovery:
  exportedTagsOnMetrics:
    AWS/ApplicationELB:
      - LoadBalancer
      - TargetGroup

  jobs:
    - type: AWS/ApplicationELB  # Application Load Balancer
      regions:
        - ap-south-1  # Adjust this to your specific region
      period: 10
      length: 120
      metrics:
        - name: RequestCount
          statistics: [Sum]
        - name: TargetResponseTime
          statistics: [Average]
        - name: HealthyHostCount
          statistics: [Average]
        - name: UnHealthyHostCount
          statistics: [Average]
        - name: HTTPCode_Target_2XX_Count
          statistics: [Sum]
        - name: HTTPCode_Target_4XX_Count
          statistics: [Sum]
        - name: HTTPCode_Target_5XX_Count
          statistics: [Sum]
        - name: HTTPCode_ELB_4XX_Count
          statistics: [Sum]
        - name: HTTPCode_ELB_5XX_Count
          statistics: [Sum]
        - name: HTTPCode_ELB_2XX_Count
          statistics: [Sum]
        - name: HTTPCode_ELB_502_Count
          statistics: [Sum]
        - name: HTTPCode_ELB_503_Count
          statistics: [Sum]
        - name: HTTPCode_ELB_504_Count
          statistics: [Sum]
        # Add more ALB metrics as needed